# Generated by Django 4.1.1 on 2023-08-08 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorgeneral',
            name='laboratorio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratorio.laboratorio'),
        ),
    ]
