# Generated by Django 4.1.1 on 2023-08-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0003_alter_directorgeneral_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorgeneral',
            name='especialidad',
            field=models.CharField(blank=True, max_length=50, verbose_name='Especialidad'),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name='Pais'),
        ),
    ]
